### ISSUE TITLE
Error using with ssh-agent: "Checking the base repository state > ERROR: repository not found"

### ISSUE THREAD

**Issue by mitchmindtree** [DeterminateSystems/update-flake-lock#102]
Hi there, thanks for your work on this!

I'm currently attempting to use the `update-flake-lock` action within a private repo workflow that depends on two other private repos. I'm using SSH key pairs to provide access between repositories using [`webfactory/ssh-agent`](https://github.com/webfactory/ssh-agent?tab=readme-ov-file#usage).

This works nicely for our regular CI build workflow, however our `update-flake-lock` workflow is failing at the `update-flake-lock` action with the following:

```
> Checking the base repository state
  /usr/bin/git symbolic-ref HEAD --short
  mitchmindtree/fix-update-flake-lock
  Working base is branch 'mitchmindtree/fix-update-flake-lock'
  /usr/bin/git remote prune origin
  ERROR: Repository not found.
  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
  Error: The process '/usr/bin/git' failed with exit code 128
  ```

I'm wondering if perhaps the `update-flake-lock` does not have access to the `ssh-agent` for some reason?

Here's the failing workflow in question:

```yml
name: update-flake-lock

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * *' # runs nightly at 00:00 UTC

jobs:
  # Updates the pint-src flake input and open a PR with the updated flake.lock.
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
              ${{ secrets.SSH_KEY_BASE }}
              ${{ secrets.SSH_KEY_PINT }}
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          inputs: pint-src
```

Fwiw, here's our other workflow that is working and passing successfully. It's basically doing the same thing, but without using `update-flake-lock`. It at least shows that our SSH access is working elsewhere:

```yml
name: pint-nix

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Check the default builds and dev envs work on both macOS and Linux.
  nix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        command: [
            "build --print-build-logs --no-update-lock-file",
            "develop --print-build-logs --no-update-lock-file",
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
              ${{ secrets.SSH_KEY_BASE }}
              ${{ secrets.SSH_KEY_PINT }}
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - run: nix ${{ matrix.command }}
```

Here is the full failing workflow log in case it helps:

[workflow-log.txt](https://github.com/DeterminateSystems/update-flake-lock/files/15194931/workflow-log.txt)

Perhaps we need to do something to forward ssh-agent access to `update-flake-lock` somehow? Or maybe this is a different issue I'm overlooking?

Any advice or ideas on what might be going on would be greatly appreciated 🙏

**Comment by cole-h** [comment]
I don't see anything obvious that would be causing your issue.

However, I have one hunch -- the error message appears to happen when we're delegating to the `peter-evans/create-pull-request` action, around where it's trying to push the update-flake-lock commit to your repository and subsequently open a PR. If your organization/repository restricts workflow permissions by default, you may need to give the job that runs update-flake-lock explicit `contents: write` and `pull-requests: write` permissions, i.e.:

```yaml
name: update-flake-lock

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * *' # runs nightly at 00:00 UTC

jobs:
  # Updates the pint-src flake input and open a PR with the updated flake.lock.
  lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
              ${{ secrets.SSH_KEY_BASE }}
              ${{ secrets.SSH_KEY_PINT }}
      - uses: DeterminateSystems/nix-installer-action@v10
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          inputs: pint-src
```

If that doesn't work, their documentation also calls out the need to make sure the repo allows GitHub Actions to create PRs in the first place (https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#workflow-permissions) by changing the setting at "Actions > General > Workflow permissions".

Would you mind trying that out and let me know how it goes?
