### ISSUE TITLE
Missing pull-request-number output

### ISSUE THREAD

**Issue by Gerg-L** [DeterminateSystems/update-flake-lock#104]
Upon updating from v20 to v21 the `outputs.pull-request-number` is missing

to reproduce

```yaml
name: flake-update
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 5 * * *' 

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v11
      - name: update
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          pr-title: "Update flake.lock" 
      - name: merge
        run: |
          gh pr merge ${{ steps.update.outputs.pull-request-number }} --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 ```
 
`${{ steps.update.outputs.pull-request-number }}` returns nothing

This same action worked with v20

Replacing `${{ steps.update.outputs.pull-request-number }}` with `$PULL_REQUEST_NUMBER` works around this issue

**Comment by lucperkins** [comment]
@Gerg-L Could you try setting the `id` of the step to `update` instead of the `name`?

```yaml
- name: Update flake lock
  id: update
  uses: DeterminateSystems/update-flake-lock@v21
  with:
    pr-title: "Update flake.lock"
```
