### ISSUE TITLE
Update private flake input

### ISSUE THREAD

**Issue by andreasfelix** [DeterminateSystems/update-flake-lock#54]
Hi, I am trying to update a flake which has a private flake as input:

```nix
{
  inputs.private.url = "git+ssh://git@github.com/org/private";
}
```

Is there a possibility to use this action to update private flake inputs? I guess the runner would somehow need ssh access to the remote repository.

**Comment by GeorgesAlkhouri** [comment]
Maybe this helps, I just added an [ssh-agent action](https://github.com/webfactory/ssh-agent) with a private ssh key that can access your private git flake repos.

https://github.com/GeorgesAlkhouri/nixos-configs/blob/main/.github/workflows/update-action.yml
```yaml
name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 23 * * *" # daily at 23:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.TOKEN }}
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GH_NIX_FLAKE_UPDATE_KEY  }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v16
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated

```
