### ISSUE TITLE
There's no way to know whether an update happened

### ISSUE THREAD

**Issue by lovesegfault** [DeterminateSystems/update-flake-lock#70]
Currently, there is no way of telling whether an update happened, which means any following actions which rely on the `pull-request-number` output just get a PR number of `0` and fail.

```yaml
      - uses: DeterminateSystems/update-flake-lock@v17
        id: update-flake
        with:
          branch: update-${{ matrix.flake }}
          commit-msg: "chore(flake/${{ matrix.flake }}): update"
          git-author-email: hatesegfault@protonmail.ch
          git-author-name: hatesegfault
          inputs: ${{ matrix.flake }}
          pr-title: "chore(flake/${{ matrix.flake }}): update"
          token: ${{ secrets.PAT }}
      - uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.update-flake.outputs.pull-request-number }}
          merge-method: rebase
```

Something like the above will fail whenever there's no update for `matrix.flake`. There should be a way to say `if: ${{ steps.update-flake.outputs.updated == 'true' }}` for follow-up steps.
