### ISSUE TITLE
README is confusing about running on PRs

### ISSUE THREAD

**Issue by andreabedini** [DeterminateSystems/update-flake-lock#80]
The README is confusing (or perhaps confused) about running the action on PRs.

```
## Example that doesn't run on PRs

If you were to run this action as a part of your CI workflow, you may want to prevent it from running against Pull Requests.

```yaml
name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  pull_request: # triggers on every Pull Request
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00
...
```

AFAIU the comment is correct and that specification will trigger on every pull-request; while the section is about **not** triggering on pull-requests. I might not understand what the auther intended to say but the other examples don't have the `on: pull_request:` and will not trigger on PRs; so maybe this section is redundant.
