### ISSUE TITLE
allow running commands after update

### ISSUE THREAD

**Issue by sellout** [DeterminateSystems/update-flake-lock#91]
I use https://github.com/sellout/project-manager in most of my repos. It generates some files that get committed, and also adds a flake check that the files are current.

Using `update-flake-lock` often creates a PR that initially fails because the updated inputs cause changes in the generated files that then fail the up-to-date check.

I would like to be able to do something like 
```yaml
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock"
          run: |
            nix develop --command project-manager switch
            git commit --all --message="Update generated files"
```
so that I don't have to manually update the PR with a new commit each time.
